PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS posts(
    postid VARCHAR(8) NOT NULL,
    created_utc DATETIME NOT NULL,
    score FLOAT,
    upvote_ratio FLOAT,
    total_awards_received FLOAT,
    author VARCHAR(64) NOT NULL,
    subreddit INTEGER NOT NULL,
    title TEXT,
    selftext TEXT,
    PRIMARY KEY (postid, author, created_utc, subreddit)
);

CREATE TABLE IF NOT EXISTS stocks(
    symbol VARCHAR(8) NOT NULL,
    utc DATETIME NOT NULL,
    open_price FLOAT,
    close_price FLOAT,
    high FLOAT,
    low FLOAT,
    volume INTEGER,
    PRIMARY KEY (utc, symbol)
);

CREATE TABLE IF NOT EXISTS emotion_to_num( 
    emotion TEXT, 
    num INTEGER NOT NULL, 
    PRIMARY KEY (emotion) 
);

CREATE TABLE IF NOT EXISTS regex_to_emotion( 
    regex TEXT, 
    is_regex INTEGER NOT NULL, 
    Function_Words INTEGER DEFAULT 0, 
    Pronouns INTEGER DEFAULT 0, 
    Personal_Pronouns INTEGER DEFAULT 0, 
    I INTEGER DEFAULT 0, 
    We INTEGER DEFAULT 0, 
    You INTEGER DEFAULT 0, 
    SheHe INTEGER DEFAULT 0, 
    They INTEGER DEFAULT 0, 
    Impersonal_Pronouns INTEGER DEFAULT 0, 
    Articles INTEGER DEFAULT 0, 
    Prepositions INTEGER DEFAULT 0, 
    Auxiliary_Verbs INTEGER DEFAULT 0, 
    Adverbs INTEGER DEFAULT 0, 
    Conjunctions INTEGER DEFAULT 0, 
    Negations INTEGER DEFAULT 0, 
    Verbs INTEGER DEFAULT 0, 
    Adjectives INTEGER DEFAULT 0, 
    Comparisons INTEGER DEFAULT 0, 
    Interrogatives INTEGER DEFAULT 0, 
    Numbers INTEGER DEFAULT 0, 
    Quantifiers INTEGER DEFAULT 0, 
    Affect INTEGER DEFAULT 0, 
    Positive_Emotions INTEGER DEFAULT 0, 
    Negative_Emotions INTEGER DEFAULT 0, 
    Anx INTEGER DEFAULT 0, 
    Anger INTEGER DEFAULT 0, 
    Sad INTEGER DEFAULT 0, 
    Social INTEGER DEFAULT 0, 
    Family INTEGER DEFAULT 0, 
    Friends INTEGER DEFAULT 0, 
    Female INTEGER DEFAULT 0, 
    Male INTEGER DEFAULT 0, 
    Cognitive_Processes INTEGER DEFAULT 0, 
    Insight INTEGER DEFAULT 0, 
    Causal INTEGER DEFAULT 0, 
    Discrepancies INTEGER DEFAULT 0, 
    Tentative INTEGER DEFAULT 0, 
    Certainty INTEGER DEFAULT 0, 
    Differentiation INTEGER DEFAULT 0, 
    Perceptual_Processes INTEGER DEFAULT 0, 
    See INTEGER DEFAULT 0, 
    Hear INTEGER DEFAULT 0, 
    Feel INTEGER DEFAULT 0, 
    Biological_Processes INTEGER DEFAULT 0, 
    Body INTEGER DEFAULT 0, 
    Health INTEGER DEFAULT 0, 
    Sexual INTEGER DEFAULT 0, 
    Ingest INTEGER DEFAULT 0, 
    Drives INTEGER DEFAULT 0, 
    Affiliation INTEGER DEFAULT 0, 
    Achievement INTEGER DEFAULT 0, 
    Power INTEGER DEFAULT 0, 
    Reward INTEGER DEFAULT 0, 
    Risk INTEGER DEFAULT 0, 
    Past_Focus INTEGER DEFAULT 0, 
    Present_Focus INTEGER DEFAULT 0, 
    Future_Focus INTEGER DEFAULT 0, 
    Relativity INTEGER DEFAULT 0, 
    Motion INTEGER DEFAULT 0, 
    Space INTEGER DEFAULT 0, 
    Time INTEGER DEFAULT 0, 
    Work INTEGER DEFAULT 0, 
    Leisure INTEGER DEFAULT 0, 
    Home INTEGER DEFAULT 0, 
    Money INTEGER DEFAULT 0, 
    Religion INTEGER DEFAULT 0, 
    Death INTEGER DEFAULT 0, 
    Informal_Language INTEGER DEFAULT 0, 
    Swear INTEGER DEFAULT 0, 
    Netspeak INTEGER DEFAULT 0, 
    Assent INTEGER DEFAULT 0, 
    Nonfluencies INTEGER DEFAULT 0, 
    Filler_Words INTEGER DEFAULT 0, 
    PRIMARY KEY (regex) 
);

CREATE TABLE IF NOT EXISTS word_to_emotion( 
    word TEXT, 
    Function_Words INTEGER DEFAULT 0, 
    Pronouns INTEGER DEFAULT 0, 
    Personal_Pronouns INTEGER DEFAULT 0, 
    I INTEGER DEFAULT 0, 
    We INTEGER DEFAULT 0, 
    You INTEGER DEFAULT 0, 
    SheHe INTEGER DEFAULT 0, 
    They INTEGER DEFAULT 0, 
    Impersonal_Pronouns INTEGER DEFAULT 0, 
    Articles INTEGER DEFAULT 0, 
    Prepositions INTEGER DEFAULT 0, 
    Auxiliary_Verbs INTEGER DEFAULT 0, 
    Adverbs INTEGER DEFAULT 0, 
    Conjunctions INTEGER DEFAULT 0, 
    Negations INTEGER DEFAULT 0, 
    Verbs INTEGER DEFAULT 0, 
    Adjectives INTEGER DEFAULT 0, 
    Comparisons INTEGER DEFAULT 0, 
    Interrogatives INTEGER DEFAULT 0, 
    Numbers INTEGER DEFAULT 0, 
    Quantifiers INTEGER DEFAULT 0, 
    Affect INTEGER DEFAULT 0, 
    Positive_Emotions INTEGER DEFAULT 0, 
    Negative_Emotions INTEGER DEFAULT 0, 
    Anx INTEGER DEFAULT 0, 
    Anger INTEGER DEFAULT 0, 
    Sad INTEGER DEFAULT 0, 
    Social INTEGER DEFAULT 0, 
    Family INTEGER DEFAULT 0, 
    Friends INTEGER DEFAULT 0, 
    Female INTEGER DEFAULT 0, 
    Male INTEGER DEFAULT 0, 
    Cognitive_Processes INTEGER DEFAULT 0, 
    Insight INTEGER DEFAULT 0, 
    Causal INTEGER DEFAULT 0, 
    Discrepancies INTEGER DEFAULT 0, 
    Tentative INTEGER DEFAULT 0, 
    Certainty INTEGER DEFAULT 0, 
    Differentiation INTEGER DEFAULT 0, 
    Perceptual_Processes INTEGER DEFAULT 0, 
    See INTEGER DEFAULT 0, 
    Hear INTEGER DEFAULT 0, 
    Feel INTEGER DEFAULT 0, 
    Biological_Processes INTEGER DEFAULT 0, 
    Body INTEGER DEFAULT 0, 
    Health INTEGER DEFAULT 0, 
    Sexual INTEGER DEFAULT 0, 
    Ingest INTEGER DEFAULT 0, 
    Drives INTEGER DEFAULT 0, 
    Affiliation INTEGER DEFAULT 0, 
    Achievement INTEGER DEFAULT 0, 
    Power INTEGER DEFAULT 0, 
    Reward INTEGER DEFAULT 0, 
    Risk INTEGER DEFAULT 0, 
    Past_Focus INTEGER DEFAULT 0, 
    Present_Focus INTEGER DEFAULT 0, 
    Future_Focus INTEGER DEFAULT 0, 
    Relativity INTEGER DEFAULT 0, 
    Motion INTEGER DEFAULT 0, 
    Space INTEGER DEFAULT 0, 
    Time INTEGER DEFAULT 0, 
    Work INTEGER DEFAULT 0, 
    Leisure INTEGER DEFAULT 0, 
    Home INTEGER DEFAULT 0, 
    Money INTEGER DEFAULT 0, 
    Religion INTEGER DEFAULT 0, 
    Death INTEGER DEFAULT 0, 
    Informal_Language INTEGER DEFAULT 0, 
    Swear INTEGER DEFAULT 0, 
    Netspeak INTEGER DEFAULT 0, 
    Assent INTEGER DEFAULT 0, 
    Nonfluencies INTEGER DEFAULT 0, 
    Filler_Words INTEGER DEFAULT 0, 
    PRIMARY KEY (word) 
);
